#############################################################################
# Makefile for building: 2DphysicsEngine
# Generated by qmake (3.0) (Qt 5.3.1)
# Project:  UniProjectTermTwo.pro
# Template: app
# Command: /opt/Qt/5.3/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile UniProjectTermTwo.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -I/usr/local/include/SDL2 -D_REENTRANT -std=c++0x -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/Qt/5.3/gcc_64/mkspecs/linux-g++ -I. -I/usr/local/include -I/src/ -I/opt/Qt/5.3/gcc_64/include -I/opt/Qt/5.3/gcc_64/include/QtCore -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/Qt/5.3/gcc_64 -Wl,-rpath,/opt/Qt/5.3/gcc_64/lib
LIBS          = $(SUBLIBS) -lGLEW -L/usr/local/lib -Wl,-rpath,/usr/local/lib -lSDL2 -L/opt/Qt/5.3/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/Qt/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Uni/main.cpp \
		src/Uni/Ball.cpp \
		src/Uni/BallControl.cpp \
		src/Uni/BallRenderer.cpp \
		src/Uni/BallGrid.cpp \
		src/Uni/MainGame.cpp \
		src/Randini/GLSLProgram.cpp \
		src/Randini/Camera2D.cpp \
		src/Randini/Errors.cpp \
		src/Randini/ImageLoader.cpp \
		src/Randini/InputControl.cpp \
		src/Randini/IOManager.cpp \
		src/Randini/picoPNG.cpp \
		src/Randini/Randini.cpp \
		src/Randini/ResourceManager.cpp \
		src/Randini/Sprite.cpp \
		src/Randini/SpriteLoader.cpp \
		src/Randini/TextureCache.cpp \
		src/Randini/Timer.cpp \
		src/Randini/Window.cpp 
OBJECTS       = main.o \
		Ball.o \
		BallControl.o \
		BallRenderer.o \
		BallGrid.o \
		MainGame.o \
		GLSLProgram.o \
		Camera2D.o \
		Errors.o \
		ImageLoader.o \
		InputControl.o \
		IOManager.o \
		picoPNG.o \
		Randini.o \
		ResourceManager.o \
		Sprite.o \
		SpriteLoader.o \
		TextureCache.o \
		Timer.o \
		Window.o
DIST          = /opt/Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		UniProjectTermTwo.pro src/Uni/main.cpp \
		src/Uni/Ball.cpp \
		src/Uni/BallControl.cpp \
		src/Uni/BallRenderer.cpp \
		src/Uni/BallGrid.cpp \
		src/Uni/MainGame.cpp \
		src/Randini/GLSLProgram.cpp \
		src/Randini/Camera2D.cpp \
		src/Randini/Errors.cpp \
		src/Randini/ImageLoader.cpp \
		src/Randini/InputControl.cpp \
		src/Randini/IOManager.cpp \
		src/Randini/picoPNG.cpp \
		src/Randini/Randini.cpp \
		src/Randini/ResourceManager.cpp \
		src/Randini/Sprite.cpp \
		src/Randini/SpriteLoader.cpp \
		src/Randini/TextureCache.cpp \
		src/Randini/Timer.cpp \
		src/Randini/Window.cpp
QMAKE_TARGET  = 2DphysicsEngine
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = 2DphysicsEngine


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: UniProjectTermTwo.pro /opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf /opt/Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/qt.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/resources.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/moc.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.3/gcc_64/mkspecs/features/lex.prf \
		UniProjectTermTwo.pro \
		/opt/Qt/5.3/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile UniProjectTermTwo.pro
/opt/Qt/5.3/gcc_64/mkspecs/features/spec_pre.prf:
/opt/Qt/5.3/gcc_64/mkspecs/common/shell-unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/linux.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt/5.3/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt/5.3/gcc_64/mkspecs/qconfig.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt/5.3/gcc_64/mkspecs/features/qt_functions.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/qt_config.prf:
/opt/Qt/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/Qt/5.3/gcc_64/mkspecs/features/spec_post.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/default_pre.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/resolve_config.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/default_post.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/warn_on.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/qt.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/resources.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/moc.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/unix/thread.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/exceptions.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/yacc.prf:
/opt/Qt/5.3/gcc_64/mkspecs/features/lex.prf:
UniProjectTermTwo.pro:
/opt/Qt/5.3/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile UniProjectTermTwo.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/2DphysicsEngine1.0.0 || mkdir -p .tmp/2DphysicsEngine1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/2DphysicsEngine1.0.0/ && $(COPY_FILE) --parents src/Randini/GLSLProgram.h src/Randini/Camera2D.h src/Randini/Errors.h src/Randini/GLTexture.h src/Randini/ImageLoader.h src/Randini/InputControl.h src/Randini/IOManager.h src/Randini/picoPNG.h src/Randini/Randini.h src/Randini/ResourceManager.h src/Randini/Sprite.h src/Randini/SpriteLoader.h src/Randini/TextureCache.h src/Randini/Timer.h src/Randini/Vertex.h src/Randini/Window.h src/Uni/Ball.h src/Uni/BallControl.h src/Uni/BallRenderer.h src/Uni/BallGrid.h src/Uni/MainGame.h .tmp/2DphysicsEngine1.0.0/ && $(COPY_FILE) --parents src/Uni/main.cpp src/Uni/Ball.cpp src/Uni/BallControl.cpp src/Uni/BallRenderer.cpp src/Uni/BallGrid.cpp src/Uni/MainGame.cpp src/Randini/GLSLProgram.cpp src/Randini/Camera2D.cpp src/Randini/Errors.cpp src/Randini/ImageLoader.cpp src/Randini/InputControl.cpp src/Randini/IOManager.cpp src/Randini/picoPNG.cpp src/Randini/Randini.cpp src/Randini/ResourceManager.cpp src/Randini/Sprite.cpp src/Randini/SpriteLoader.cpp src/Randini/TextureCache.cpp src/Randini/Timer.cpp src/Randini/Window.cpp .tmp/2DphysicsEngine1.0.0/ && (cd `dirname .tmp/2DphysicsEngine1.0.0` && $(TAR) 2DphysicsEngine1.0.0.tar 2DphysicsEngine1.0.0 && $(COMPRESS) 2DphysicsEngine1.0.0.tar) && $(MOVE) `dirname .tmp/2DphysicsEngine1.0.0`/2DphysicsEngine1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/2DphysicsEngine1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: src/Uni/main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/Uni/main.cpp

Ball.o: src/Uni/Ball.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Ball.o src/Uni/Ball.cpp

BallControl.o: src/Uni/BallControl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BallControl.o src/Uni/BallControl.cpp

BallRenderer.o: src/Uni/BallRenderer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BallRenderer.o src/Uni/BallRenderer.cpp

BallGrid.o: src/Uni/BallGrid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BallGrid.o src/Uni/BallGrid.cpp

MainGame.o: src/Uni/MainGame.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainGame.o src/Uni/MainGame.cpp

GLSLProgram.o: src/Randini/GLSLProgram.cpp src/Randini/GLSLProgram.h \
		src/Randini/Errors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GLSLProgram.o src/Randini/GLSLProgram.cpp

Camera2D.o: src/Randini/Camera2D.cpp src/Randini/Camera2D.h \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/core/_fixes.hpp \
		/usr/local/include/glm/core/setup.hpp \
		/usr/local/include/glm/core/_detail.hpp \
		/usr/local/include/glm/core/_vectorize.hpp \
		/usr/local/include/glm/core/type.hpp \
		/usr/local/include/glm/core/type_half.hpp \
		/usr/local/include/glm/core/type_half.inl \
		/usr/local/include/glm/core/type_float.hpp \
		/usr/local/include/glm/core/type_int.hpp \
		/usr/local/include/glm/core/type_gentype.hpp \
		/usr/local/include/glm/core/type_size.hpp \
		/usr/local/include/glm/core/type_vec1.hpp \
		/usr/local/include/glm/core/type_vec.hpp \
		/usr/local/include/glm/core/_swizzle.hpp \
		/usr/local/include/glm/core/_swizzle_func.hpp \
		/usr/local/include/glm/core/type_vec1.inl \
		/usr/local/include/glm/core/type_vec2.hpp \
		/usr/local/include/glm/core/type_vec2.inl \
		/usr/local/include/glm/core/type_vec3.hpp \
		/usr/local/include/glm/core/type_vec3.inl \
		/usr/local/include/glm/core/type_vec4.hpp \
		/usr/local/include/glm/core/type_vec4.inl \
		/usr/local/include/glm/core/type_mat2x2.hpp \
		/usr/local/include/glm/core/type_mat.hpp \
		/usr/local/include/glm/core/type_mat2x2.inl \
		/usr/local/include/glm/core/type_mat2x3.hpp \
		/usr/local/include/glm/core/type_mat2x3.inl \
		/usr/local/include/glm/core/type_mat2x4.hpp \
		/usr/local/include/glm/core/type_mat2x4.inl \
		/usr/local/include/glm/core/type_mat3x2.hpp \
		/usr/local/include/glm/core/type_mat3x2.inl \
		/usr/local/include/glm/core/type_mat3x3.hpp \
		/usr/local/include/glm/core/type_mat3x3.inl \
		/usr/local/include/glm/core/type_mat3x4.hpp \
		/usr/local/include/glm/core/type_mat3x4.inl \
		/usr/local/include/glm/core/type_mat4x2.hpp \
		/usr/local/include/glm/core/type_mat4x2.inl \
		/usr/local/include/glm/core/type_mat4x3.hpp \
		/usr/local/include/glm/core/type_mat4x3.inl \
		/usr/local/include/glm/core/type_mat4x4.hpp \
		/usr/local/include/glm/core/type_mat4x4.inl \
		/usr/local/include/glm/core/func_trigonometric.hpp \
		/usr/local/include/glm/core/func_trigonometric.inl \
		/usr/local/include/glm/core/func_exponential.hpp \
		/usr/local/include/glm/core/func_exponential.inl \
		/usr/local/include/glm/core/func_common.hpp \
		/usr/local/include/glm/core/func_common.inl \
		/usr/local/include/glm/core/func_packing.hpp \
		/usr/local/include/glm/core/func_packing.inl \
		/usr/local/include/glm/core/func_geometric.hpp \
		/usr/local/include/glm/core/func_geometric.inl \
		/usr/local/include/glm/core/func_matrix.hpp \
		/usr/local/include/glm/core/func_matrix.inl \
		/usr/local/include/glm/core/func_vector_relational.hpp \
		/usr/local/include/glm/core/func_vector_relational.inl \
		/usr/local/include/glm/core/func_integer.hpp \
		/usr/local/include/glm/core/func_integer.inl \
		/usr/local/include/glm/core/func_noise.hpp \
		/usr/local/include/glm/core/func_noise.inl \
		/usr/local/include/glm/gtc/matrix_transform.hpp \
		/usr/local/include/glm/gtc/matrix_transform.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Camera2D.o src/Randini/Camera2D.cpp

Errors.o: src/Randini/Errors.cpp src/Randini/Errors.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Errors.o src/Randini/Errors.cpp

ImageLoader.o: src/Randini/ImageLoader.cpp src/Randini/ImageLoader.h \
		src/Randini/GLTexture.h \
		src/Randini/picoPNG.h \
		src/Randini/IOManager.h \
		src/Randini/Errors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ImageLoader.o src/Randini/ImageLoader.cpp

InputControl.o: src/Randini/InputControl.cpp src/Randini/InputControl.h \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/core/_fixes.hpp \
		/usr/local/include/glm/core/setup.hpp \
		/usr/local/include/glm/core/_detail.hpp \
		/usr/local/include/glm/core/_vectorize.hpp \
		/usr/local/include/glm/core/type.hpp \
		/usr/local/include/glm/core/type_half.hpp \
		/usr/local/include/glm/core/type_half.inl \
		/usr/local/include/glm/core/type_float.hpp \
		/usr/local/include/glm/core/type_int.hpp \
		/usr/local/include/glm/core/type_gentype.hpp \
		/usr/local/include/glm/core/type_size.hpp \
		/usr/local/include/glm/core/type_vec1.hpp \
		/usr/local/include/glm/core/type_vec.hpp \
		/usr/local/include/glm/core/_swizzle.hpp \
		/usr/local/include/glm/core/_swizzle_func.hpp \
		/usr/local/include/glm/core/type_vec1.inl \
		/usr/local/include/glm/core/type_vec2.hpp \
		/usr/local/include/glm/core/type_vec2.inl \
		/usr/local/include/glm/core/type_vec3.hpp \
		/usr/local/include/glm/core/type_vec3.inl \
		/usr/local/include/glm/core/type_vec4.hpp \
		/usr/local/include/glm/core/type_vec4.inl \
		/usr/local/include/glm/core/type_mat2x2.hpp \
		/usr/local/include/glm/core/type_mat.hpp \
		/usr/local/include/glm/core/type_mat2x2.inl \
		/usr/local/include/glm/core/type_mat2x3.hpp \
		/usr/local/include/glm/core/type_mat2x3.inl \
		/usr/local/include/glm/core/type_mat2x4.hpp \
		/usr/local/include/glm/core/type_mat2x4.inl \
		/usr/local/include/glm/core/type_mat3x2.hpp \
		/usr/local/include/glm/core/type_mat3x2.inl \
		/usr/local/include/glm/core/type_mat3x3.hpp \
		/usr/local/include/glm/core/type_mat3x3.inl \
		/usr/local/include/glm/core/type_mat3x4.hpp \
		/usr/local/include/glm/core/type_mat3x4.inl \
		/usr/local/include/glm/core/type_mat4x2.hpp \
		/usr/local/include/glm/core/type_mat4x2.inl \
		/usr/local/include/glm/core/type_mat4x3.hpp \
		/usr/local/include/glm/core/type_mat4x3.inl \
		/usr/local/include/glm/core/type_mat4x4.hpp \
		/usr/local/include/glm/core/type_mat4x4.inl \
		/usr/local/include/glm/core/func_trigonometric.hpp \
		/usr/local/include/glm/core/func_trigonometric.inl \
		/usr/local/include/glm/core/func_exponential.hpp \
		/usr/local/include/glm/core/func_exponential.inl \
		/usr/local/include/glm/core/func_common.hpp \
		/usr/local/include/glm/core/func_common.inl \
		/usr/local/include/glm/core/func_packing.hpp \
		/usr/local/include/glm/core/func_packing.inl \
		/usr/local/include/glm/core/func_geometric.hpp \
		/usr/local/include/glm/core/func_geometric.inl \
		/usr/local/include/glm/core/func_matrix.hpp \
		/usr/local/include/glm/core/func_matrix.inl \
		/usr/local/include/glm/core/func_vector_relational.hpp \
		/usr/local/include/glm/core/func_vector_relational.inl \
		/usr/local/include/glm/core/func_integer.hpp \
		/usr/local/include/glm/core/func_integer.inl \
		/usr/local/include/glm/core/func_noise.hpp \
		/usr/local/include/glm/core/func_noise.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputControl.o src/Randini/InputControl.cpp

IOManager.o: src/Randini/IOManager.cpp src/Randini/IOManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IOManager.o src/Randini/IOManager.cpp

picoPNG.o: src/Randini/picoPNG.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o picoPNG.o src/Randini/picoPNG.cpp

Randini.o: src/Randini/Randini.cpp src/Randini/Randini.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Randini.o src/Randini/Randini.cpp

ResourceManager.o: src/Randini/ResourceManager.cpp src/Randini/ResourceManager.h \
		src/Randini/TextureCache.h \
		src/Randini/GLTexture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ResourceManager.o src/Randini/ResourceManager.cpp

Sprite.o: src/Randini/Sprite.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Sprite.o src/Randini/Sprite.cpp

SpriteLoader.o: src/Randini/SpriteLoader.cpp src/Randini/SpriteLoader.h \
		src/Randini/Vertex.h \
		/usr/local/include/glm/glm.hpp \
		/usr/local/include/glm/core/_fixes.hpp \
		/usr/local/include/glm/core/setup.hpp \
		/usr/local/include/glm/core/_detail.hpp \
		/usr/local/include/glm/core/_vectorize.hpp \
		/usr/local/include/glm/core/type.hpp \
		/usr/local/include/glm/core/type_half.hpp \
		/usr/local/include/glm/core/type_half.inl \
		/usr/local/include/glm/core/type_float.hpp \
		/usr/local/include/glm/core/type_int.hpp \
		/usr/local/include/glm/core/type_gentype.hpp \
		/usr/local/include/glm/core/type_size.hpp \
		/usr/local/include/glm/core/type_vec1.hpp \
		/usr/local/include/glm/core/type_vec.hpp \
		/usr/local/include/glm/core/_swizzle.hpp \
		/usr/local/include/glm/core/_swizzle_func.hpp \
		/usr/local/include/glm/core/type_vec1.inl \
		/usr/local/include/glm/core/type_vec2.hpp \
		/usr/local/include/glm/core/type_vec2.inl \
		/usr/local/include/glm/core/type_vec3.hpp \
		/usr/local/include/glm/core/type_vec3.inl \
		/usr/local/include/glm/core/type_vec4.hpp \
		/usr/local/include/glm/core/type_vec4.inl \
		/usr/local/include/glm/core/type_mat2x2.hpp \
		/usr/local/include/glm/core/type_mat.hpp \
		/usr/local/include/glm/core/type_mat2x2.inl \
		/usr/local/include/glm/core/type_mat2x3.hpp \
		/usr/local/include/glm/core/type_mat2x3.inl \
		/usr/local/include/glm/core/type_mat2x4.hpp \
		/usr/local/include/glm/core/type_mat2x4.inl \
		/usr/local/include/glm/core/type_mat3x2.hpp \
		/usr/local/include/glm/core/type_mat3x2.inl \
		/usr/local/include/glm/core/type_mat3x3.hpp \
		/usr/local/include/glm/core/type_mat3x3.inl \
		/usr/local/include/glm/core/type_mat3x4.hpp \
		/usr/local/include/glm/core/type_mat3x4.inl \
		/usr/local/include/glm/core/type_mat4x2.hpp \
		/usr/local/include/glm/core/type_mat4x2.inl \
		/usr/local/include/glm/core/type_mat4x3.hpp \
		/usr/local/include/glm/core/type_mat4x3.inl \
		/usr/local/include/glm/core/type_mat4x4.hpp \
		/usr/local/include/glm/core/type_mat4x4.inl \
		/usr/local/include/glm/core/func_trigonometric.hpp \
		/usr/local/include/glm/core/func_trigonometric.inl \
		/usr/local/include/glm/core/func_exponential.hpp \
		/usr/local/include/glm/core/func_exponential.inl \
		/usr/local/include/glm/core/func_common.hpp \
		/usr/local/include/glm/core/func_common.inl \
		/usr/local/include/glm/core/func_packing.hpp \
		/usr/local/include/glm/core/func_packing.inl \
		/usr/local/include/glm/core/func_geometric.hpp \
		/usr/local/include/glm/core/func_geometric.inl \
		/usr/local/include/glm/core/func_matrix.hpp \
		/usr/local/include/glm/core/func_matrix.inl \
		/usr/local/include/glm/core/func_vector_relational.hpp \
		/usr/local/include/glm/core/func_vector_relational.inl \
		/usr/local/include/glm/core/func_integer.hpp \
		/usr/local/include/glm/core/func_integer.inl \
		/usr/local/include/glm/core/func_noise.hpp \
		/usr/local/include/glm/core/func_noise.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpriteLoader.o src/Randini/SpriteLoader.cpp

TextureCache.o: src/Randini/TextureCache.cpp src/Randini/TextureCache.h \
		src/Randini/GLTexture.h \
		src/Randini/ImageLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextureCache.o src/Randini/TextureCache.cpp

Timer.o: src/Randini/Timer.cpp src/Randini/Timer.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Timer.o src/Randini/Timer.cpp

Window.o: src/Randini/Window.cpp src/Randini/Window.h \
		/usr/local/include/SDL2/SDL.h \
		/usr/local/include/SDL2/SDL_main.h \
		/usr/local/include/SDL2/SDL_stdinc.h \
		/usr/local/include/SDL2/SDL_config.h \
		/usr/local/include/SDL2/SDL_platform.h \
		/usr/local/include/SDL2/begin_code.h \
		/usr/local/include/SDL2/close_code.h \
		/usr/local/include/SDL2/SDL_assert.h \
		/usr/local/include/SDL2/SDL_atomic.h \
		/usr/local/include/SDL2/SDL_audio.h \
		/usr/local/include/SDL2/SDL_error.h \
		/usr/local/include/SDL2/SDL_endian.h \
		/usr/local/include/SDL2/SDL_mutex.h \
		/usr/local/include/SDL2/SDL_thread.h \
		/usr/local/include/SDL2/SDL_rwops.h \
		/usr/local/include/SDL2/SDL_clipboard.h \
		/usr/local/include/SDL2/SDL_cpuinfo.h \
		/usr/local/include/SDL2/SDL_events.h \
		/usr/local/include/SDL2/SDL_video.h \
		/usr/local/include/SDL2/SDL_pixels.h \
		/usr/local/include/SDL2/SDL_rect.h \
		/usr/local/include/SDL2/SDL_surface.h \
		/usr/local/include/SDL2/SDL_blendmode.h \
		/usr/local/include/SDL2/SDL_keyboard.h \
		/usr/local/include/SDL2/SDL_keycode.h \
		/usr/local/include/SDL2/SDL_scancode.h \
		/usr/local/include/SDL2/SDL_mouse.h \
		/usr/local/include/SDL2/SDL_joystick.h \
		/usr/local/include/SDL2/SDL_gamecontroller.h \
		/usr/local/include/SDL2/SDL_quit.h \
		/usr/local/include/SDL2/SDL_gesture.h \
		/usr/local/include/SDL2/SDL_touch.h \
		/usr/local/include/SDL2/SDL_haptic.h \
		/usr/local/include/SDL2/SDL_hints.h \
		/usr/local/include/SDL2/SDL_loadso.h \
		/usr/local/include/SDL2/SDL_log.h \
		/usr/local/include/SDL2/SDL_messagebox.h \
		/usr/local/include/SDL2/SDL_power.h \
		/usr/local/include/SDL2/SDL_render.h \
		/usr/local/include/SDL2/SDL_system.h \
		/usr/local/include/SDL2/SDL_timer.h \
		/usr/local/include/SDL2/SDL_version.h \
		src/Randini/Errors.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Window.o src/Randini/Window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

